name: Helm Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name, if different
  # You can customize the triggers to match your needs.

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose the runner platform that suits your needs.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/kubernetes-action@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}  # Create a GitHub secret named KUBE_CONFIG_DATA with your kubeconfig data.


      - name: Deploy Helm Chart
        run: |
          helm upgrade --install my-app .
